export enum RequestStatus {
  SUCCESS = "SUCCESS",
  ERROR = "ERROR",
  IDLE = "IDLE",
  LOADING = "LOADING",
  UNAUTHORIZED = "UNAUTHORIZED",
  USER_NOT_FOUND = "USER_NOT_FOUND",
  USER_NOT_APPROVED = "USER_NOT_APPROVED",
  REQUEST_LINK_SENT = "REQUEST_LINK_SENT",
  INTERNAL_SERVER_ERROR = "INTERNAL_SERVER_ERROR",
  TOKEN_MISSING = "TOKEN_MISSING",
  INVALID_OR_EXPIRED_TOKEN = "INVALID_OR_EXPIRED_TOKEN",
}
