export enum RequestStatus {
  CREATE_SUCCESS = "CREATE_SUCCESS",
  CREATE_ERROR = "CREATE_ERROR",
  UPDATE_SUCCESS = "UPDATE_SUCCESS",
  UPDATE_ERROR = "UPDATE_ERROR",
  DELETE_SUCCESS = "DELETE_SUCCESS",
  DELETE_ERROR = "DELETE_ERROR",
  GET_SUCCESS = "GET_SUCCESS",
  GET_ERROR = "GET_ERROR",
  INTERNAL_SERVER_ERROR = "INTERNAL_SERVER_ERROR",
  TOKEN_MISSING = "TOKEN_MISSING",
  INVALID_OR_EXPIRED_TOKEN = "INVALID_OR_EXPIRED_TOKEN",
}
