export enum NotificationType {
    ADDED_TO_WAITING_LIST = "ADDED_TO_WAITING_LIST",
    CLASS_BOOKED = "CLASS_BOOKED",
    CLASS_CANCELLED = "CLASS_CANCELLED",
    CLASS_SPOT_OPENED = "CLASS_SPOT_OPENED"
}